.Dd 02/04/19
.Dt cocoasudo 1
.Os Darwin
.Sh NAME
.Nm cocoasudo
.Nd sudo with a GUI
.Sh SYNOPSIS
.Nm
.Op Fl Fl icon=icon.tiff
.Op Fl Fl prompt=prompt
.Op Fl Fl sessid=sessid
 command ...
.Sh DESCRIPTION
.Nm cocoasudo
is a GUI alternative to \fBsudo\fR for macOS.
.sp
.Ar THIS
version, especially, is up-to-date with Apple's modern pattern of obtaining administrator privileges (SMJobBless/XPC).
.sp
Therefore, it is (supposedly) safer than its predecessor:
.Ar (http://www.performantdesign.com/2009/10/26/cocoasudo-a-graphical-cocoa-based-alternative-to-sudo/).
.Pp
\fBArguments:\fR
.Bl -tag -width -indent
.It Fl Fl icon
optional argument to specify a custom icon
.It Fl Fl prompt
optional argument to specify a custom prompt
.It Fl Fl sessid
optional argument to specify the already-authenticated SESSION ID (a number) to which we should bind this cocoasudo call.
.sp
Important notice: XXX SESSIONS
.It \fBcommand\fR
A command like \fI"mkdir /temp"\fR.
.El
.Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr sudo 8
.Sh BUGS
May have security vurnerabilities or other bugs of some sort because it uses the NSAuthenticatedTask library (an experimental library).
For support please report to:
.sp
.Ar https://github.com/npyl/cocoasudo/issues
.Sh HISTORY
cocoasudo was first created by Aaron Kardell in 2009.
.sp
Bugfixes and patches to work for newer macOS versions by \fBkalikaneko\fR, \fBgetlantern\fR.
.sp
2019: patched by \fBnpyl\fR (https://github.com/npyl) to leverage newer macOS security features such as (SMJobBless/XPC).